# Generated by Django 4.1.5 on 2023-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Banner Image'),
        ),
    ]
