# Generated by Django 4.1.3 on 2023-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_path',
            field=models.FileField(blank=True, null=True, upload_to='movie/'),
        ),
    ]
