# Generated by Django 4.1.3 on 2023-09-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0003_tvseries_episodes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Episodes',
            new_name='Episode',
        ),
    ]
