# Generated by Django 4.1.3 on 2023-09-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0004_rename_episodes_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_series', to='streaming_app.tvseries'),
        ),
    ]
