# Generated by Django 4.1.3 on 2023-09-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0005_alter_episode_tv_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='streaming_app.tvseries'),
        ),
    ]
