# Generated by Django 4.2.1 on 2023-09-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0006_alter_episode_tv_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseries',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='price',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
    ]
