# Generated by Django 4.2.1 on 2023-09-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0007_alter_tvseries_discount_alter_tvseries_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trending',
            field=models.CharField(choices=[('', ''), ('Trending', 'Trending'), ('Latest', 'Latest')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='trending',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Trending', 'Trending'), ('Latest', 'Latest')], default='Normal', max_length=80),
        ),
    ]
