# Generated by Django 4.2.1 on 2023-09-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0008_alter_movie_trending_alter_movie_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('hls_playlist', models.FileField(blank=True, null=True, upload_to='hls/')),
            ],
        ),
    ]
