# Generated by Django 4.1.5 on 2023-06-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date')),
                ('iso3', models.CharField(max_length=50, verbose_name='ISO3')),
                ('name', models.CharField(max_length=50, verbose_name='NAME')),
                ('unit', models.IntegerField(default=1, verbose_name='Unit')),
                ('buy', models.FloatField(verbose_name='Buy')),
                ('sell', models.FloatField(verbose_name='Sell')),
            ],
        ),
    ]
