# Generated by Django 4.1.3 on 2023-08-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingsdata',
            name='app_store_icon',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='app_store_link',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='background_image',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='background_image_second',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='customer_video',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='customer_video_label',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='desc',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='follow_up_desc',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='follow_up_label',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='mobile_logo',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='play_store_icon',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='play_store_link',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='title',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='sitesettingsdata',
            name='what_you_can_do_desc',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='stepstostartup',
            name='desc',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='stepstostartup',
            name='title',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='label',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='link',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='whatyoucando',
            name='fontawesome_icon',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='whatyoucando',
            name='label',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='desc',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='fontawesome_icon',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='title',
            field=models.CharField(default='default', max_length=256),
        ),
    ]
