# Generated by Django 4.1.3 on 2023-08-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitesettingsdata_app_store_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettingsdata',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='sitesettingsdata',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='sitesettingsdata',
            name='whyus',
        ),
        migrations.AddField(
            model_name='stepstostartup',
            name='sitesetting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='setps', to='website.sitesettingsdata'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='sitesetting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='website.sitesettingsdata'),
        ),
        migrations.AddField(
            model_name='whatyoucando',
            name='sitesetting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whatyoucando', to='website.sitesettingsdata'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='sitesetting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='why_us', to='website.sitesettingsdata'),
        ),
        migrations.AlterField(
            model_name='sitesettingsdata',
            name='what_you_can_do',
            field=models.CharField(default='default', max_length=256),
        ),
    ]
