# Generated by Django 4.1.3 on 2023-08-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sitesettingsdata_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettingsdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
