# Generated by Django 4.2.1 on 2023-09-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionfeature_remove_subscription_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='features',
        ),
    ]
