# Generated by Django 4.2.1 on 2023-09-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videouploadpp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to='hls/'),
        ),
    ]
