# Generated by Django 4.2.1 on 2023-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
