# Generated by Django 4.2.1 on 2023-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0002_customuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
