# Generated by Django 4.2.1 on 2023-09-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userr', '0002_customuser_counter_customuser_email_verified'),
        ('userr', '0003_customuser_counter'),
    ]

    operations = [
    ]
